Repository AnyImageKit/AnyImageKit, pull requests merged in 2020-10, with the labels that each got.

#27 Add Documentation
  AnyImageKit.xcodeproj/project.pbxproj
  Documentation/README_CN.md
  Documentation/RELEASE_NOTE.md
  Documentation/RELEASE_NOTE_CN.md
  Documentation/Wiki/Capture使用说明.md
  Documentation/Wiki/Editor使用说明.md
  Documentation/Wiki/Home.md
  Documentation/Wiki/Picker使用说明.md
  Documentation/Wiki/slidebar.md
  Documentation/Wiki/使用说明.md
  Documentation/Wiki/安装说明.md
  Example/Info.plist
  README.md
Labels: documentation

#30 Documentation
  Documentation/RELEASE_NOTE.md
  Documentation/RELEASE_NOTE_CN.md
  Documentation/Wiki/Home.md
  Documentation/Wiki/slidebar.md
Labels: documentation

#35 Feature Preselect Assets
  AnyImageKit.xcodeproj/project.pbxproj
  Documentation/Wiki/Home.md
  Documentation/Wiki/Picker使用说明.md
  Documentation/Wiki/slidebar.md
  Example/AppDelegate.swift
  Example/Controller/AvatarPickerController.swift
  Example/Controller/HomeViewController.swift
  Example/Controller/PreselectAssetViewController.swift
  Example/Resources/en.lproj/Localizable.strings
  Example/Resources/zh-Hans.lproj/Localizable.strings
  Sources/AnyImageKit/Capture/View/CaptureFocusView.swift
  Sources/AnyImageKit/Capture/View/CapturePreviewView.swift
  Sources/AnyImageKit/Core/Extension/Core+UIColor.swift
  Sources/AnyImageKit/Editor/Controller/InputTextViewController.swift
  Sources/AnyImageKit/Editor/Controller/PhotoEditorController.swift
  Sources/AnyImageKit/Editor/Controller/VideoEditorController.swift
  Sources/AnyImageKit/Editor/View/Cell/EditorCropOptionCell.swift
  Sources/AnyImageKit/Editor/View/EditorCropToolView.swift
  Sources/AnyImageKit/Editor/View/EditorEditOptionsView.swift
  Sources/AnyImageKit/Editor/View/EditorMosaicToolView.swift
  Sources/AnyImageKit/Editor/View/EditorPenToolView.swift
  Sources/AnyImageKit/Editor/View/EditorTextToolView.swift
  Sources/AnyImageKit/Editor/View/EditorToolView.swift
  Sources/AnyImageKit/Editor/View/Kit/ColorButton.swift
  Sources/AnyImageKit/Editor/View/Kit/TextImageView.swift
  Sources/AnyImageKit/Editor/View/PhotoEditorContentView+Crop.swift
  Sources/AnyImageKit/Editor/View/VideoEditorCropProgressView.swift
  Sources/AnyImageKit/Editor/View/VideoEditorCropToolView.swift
  Sources/AnyImageKit/Editor/View/VideoEditorToolView.swift
  Sources/AnyImageKit/Picker/Controller/AssetPickerViewController.swift
  Sources/AnyImageKit/Picker/Controller/ImagePickerController.swift
  Sources/AnyImageKit/Picker/Model/Asset.swift
  Sources/AnyImageKit/Picker/PickerOptionsInfo.swift
  Sources/AnyImageKit/Picker/View/Cell/CameraCell.swift
  Sources/AnyImageKit/Picker/View/Cell/PhotoLivePreviewCell.swift
  Sources/AnyImageKit/Picker/View/Kit/NumberCircleButton.swift
  Sources/AnyImageKit/Picker/View/Kit/OriginalButton.swift
  Sources/AnyImageKit/Picker/View/PermissionLimitedView.swift
  Sources/AnyImageKit/Picker/View/PickerToolBar.swift
Labels: enhancement

#33 feat: data track
  AnyImageKit.podspec
  AnyImageKit.xcodeproj/project.pbxproj
  Documentation/DATA_TRACK.md
  Documentation/RELEASE_NOTE.md
  Documentation/RELEASE_NOTE_CN.md
  Example/Controller/CaptureConfigViewController.swift
  Example/Controller/EditorConfigViewController.swift
  Example/Controller/PickerConfigViewController.swift
  Package.swift
  Sources/AnyImageKit/Capture/Controller/CaptureViewController.swift
  Sources/AnyImageKit/Capture/Controller/ImageCaptureController.swift
  Sources/AnyImageKit/Capture/Controller/PadCaptureViewController.swift
  Sources/AnyImageKit/Capture/Extension/Capture+DataTrack.swift
  Sources/AnyImageKit/Core/Controller/AnyImageNavigationController.swift
  Sources/AnyImageKit/Core/Controller/AnyImageViewController.swift
  Sources/AnyImageKit/Core/Util/DataTrack/AnyImageEvent.swift
  Sources/AnyImageKit/Core/Util/DataTrack/AnyImagePage.swift
  Sources/AnyImageKit/Core/Util/DataTrack/DataTrackObserver.swift
  Sources/AnyImageKit/Core/Util/DataTrack/ImageKitDataTrackDelegate.swift
  Sources/AnyImageKit/Editor/Controller/ImageEditorController.swift
  Sources/AnyImageKit/Editor/Controller/PhotoEditorController.swift
  Sources/AnyImageKit/Editor/Extension/Editor+DataTrack.swift
  Sources/AnyImageKit/Picker/Controller/AssetPickerViewController+Capture.swift
  Sources/AnyImageKit/Picker/Controller/ImagePickerController.swift
  Sources/AnyImageKit/Picker/Controller/PhotoPreviewController.swift
  Sources/AnyImageKit/Picker/Extension/Picker+DataTrack.swift
Labels: enhancement

#40 fix: Picker can't scroll to end when switch album
  Sources/AnyImageKit/Picker/Controller/AssetPickerViewController.swift
Labels: bug

#45 fix: preview video without progress
  Example/Controller/PickerResultViewController.swift
  Sources/AnyImageKit/Core/Util/Export/ExportTool+Video.swift
  Sources/AnyImageKit/Core/Util/Export/ExportTool+VideoURL.swift
Labels: bug
