Repository AnyImageKit/AnyImageKit, pull requests merged in 2021-04, with the labels that each got.

#89 feat: improve optional options
  AnyImageKit.podspec
  AnyImageKit.xcodeproj/project.pbxproj
  Podfile
  Podfile.lock
  Sources/AnyImageKit/Core/Util/Cache/ImageCacheTool.swift
  Sources/AnyImageKit/Core/Util/Common/BundleHelper.swift
  Sources/AnyImageKit/Editor/View/Photo/Cell/EditorCropOptionCell.swift
  Sources/AnyImageKit/Picker/Controller/AlbumPickerViewController.swift
  Sources/AnyImageKit/Picker/Controller/AssetPickerViewController.swift
  Sources/AnyImageKit/Picker/Controller/ImagePickerController.swift
  Sources/AnyImageKit/Picker/Controller/PhotoPreviewController.swift
  Sources/AnyImageKit/Picker/Extension/Picker+MediaType.swift
  Sources/AnyImageKit/Picker/Extension/Picker+PHAsset.swift
  Sources/AnyImageKit/Picker/Extension/Picker+UIBlurEffect.swift
  Sources/AnyImageKit/Picker/Extension/Picker+UIColor.swift
  Sources/AnyImageKit/Picker/Extension/Picker+UIStatusBarStyle.swift
  Sources/AnyImageKit/Picker/PickerOptionsConfigurable.swift
  Sources/AnyImageKit/Picker/PickerOptionsInfo.swift
  Sources/AnyImageKit/Picker/PickerTheme.swift
  Sources/AnyImageKit/Picker/View/Cell/AlbumCell.swift
  Sources/AnyImageKit/Picker/View/Cell/AssetCell.swift
  Sources/AnyImageKit/Picker/View/Cell/CameraCell.swift
  Sources/AnyImageKit/Picker/View/Cell/PhotoGIFPreviewCell.swift
  Sources/AnyImageKit/Picker/View/Cell/PhotoLivePreviewCell.swift
  Sources/AnyImageKit/Picker/View/Cell/PhotoPreviewCell.swift
  Sources/AnyImageKit/Picker/View/Cell/PreviewCell.swift
  Sources/AnyImageKit/Picker/View/Cell/VideoPreviewCell.swift
  Sources/AnyImageKit/Picker/View/Kit/LivePhotoTipView.swift
  Sources/AnyImageKit/Picker/View/Kit/LoadingiCloudView.swift
  Sources/AnyImageKit/Picker/View/Kit/NumberCircleButton.swift
  Sources/AnyImageKit/Picker/View/Kit/OriginalButton.swift
  Sources/AnyImageKit/Picker/View/Kit/PickerArrowButton.swift
  Sources/AnyImageKit/Picker/View/PermissionDeniedView.swift
  Sources/AnyImageKit/Picker/View/PermissionLimitedView.swift
  Sources/AnyImageKit/Picker/View/PickerPreviewIndexView.swift
  Sources/AnyImageKit/Picker/View/PickerPreviewNavigationBar.swift
  Sources/AnyImageKit/Picker/View/PickerToolBar.swift
  Sources/AnyImageKit/Resources/Picker/Picker.xcassets/CheckOff.imageset/CheckOff.png
  Sources/AnyImageKit/Resources/Picker/Picker.xcassets/CheckOff.imageset/CheckOff@2x.png
  Sources/AnyImageKit/Resources/Picker/Picker.xcassets/CheckOff.imageset/CheckOff@3x.png
  Sources/AnyImageKit/Resources/Picker/Picker.xcassets/CheckOff.imageset/Contents.json
  Sources/AnyImageKit/Resources/Picker/Picker.xcassets/CheckOn.imageset/CheckOn.png
  Sources/AnyImageKit/Resources/Picker/Picker.xcassets/CheckOn.imageset/CheckOn@2x.png
  Sources/AnyImageKit/Resources/Picker/Picker.xcassets/CheckOn.imageset/CheckOn@3x.png
  Sources/AnyImageKit/Resources/Picker/Picker.xcassets/CheckOn.imageset/Contents.json
Labels: enhancement

#91 Fix animation error when cropping square image
  Sources/AnyImageKit/Editor/View/Photo/PhotoEditorContentView+Crop.swift
Labels: bug

#92 Docs: Update public remarks
  AnyImageKit.xcodeproj/project.pbxproj
  Sources/AnyImageKit/Capture/CaptureOptionsInfo.swift
  Sources/AnyImageKit/Capture/CaptureResult.swift
  Sources/AnyImageKit/Capture/Option/CaptureAspectRatio.swift
  Sources/AnyImageKit/Capture/Option/CaptureFlashMode.swift
  Sources/AnyImageKit/Capture/Option/CaptureMediaOption.swift
  Sources/AnyImageKit/Capture/Option/CapturePosition.swift
  Sources/AnyImageKit/Capture/Option/CapturePreset.swift
  Sources/AnyImageKit/Editor/EditorOptionsInfo.swift
  Sources/AnyImageKit/Editor/EditorPhotoOptionsInfo.swift
  Sources/AnyImageKit/Editor/EditorResult.swift
  Sources/AnyImageKit/Editor/EditorVideoOptionsInfo.swift
  Sources/AnyImageKit/Editor/Option/EditorCropOption.swift
  Sources/AnyImageKit/Editor/Option/EditorMosaicOption.swift
  Sources/AnyImageKit/Editor/Option/EditorPenColorOption.swift
  Sources/AnyImageKit/Editor/Option/EditorPhotoToolOption.swift
  Sources/AnyImageKit/Editor/Option/EditorTextColor.swift
  Sources/AnyImageKit/Editor/Option/EditorVideoToolOption.swift
Labels: documentation
