Repository AnyImageKit/AnyImageKit, pull requests merged in 2021-11, with the labels that each got.

#113 Disable rule
  Sources/AnyImageKit/Picker/Controller/AssetPickerViewController+Editor.swift
  Sources/AnyImageKit/Picker/Controller/AssetPickerViewController.swift
  Sources/AnyImageKit/Picker/Controller/PhotoPreviewController.swift
  Sources/AnyImageKit/Picker/Model/Asset.swift
  Sources/AnyImageKit/Picker/Model/AssetDisableCheckRule.swift
  Sources/AnyImageKit/Picker/View/Cell/AssetCell.swift
  Sources/AnyImageKit/Resources/Picker/en.lproj/Picker.strings
  Sources/AnyImageKit/Resources/Picker/pt-BR.lproj/Picker.strings
  Sources/AnyImageKit/Resources/Picker/tr.lproj/Picker.strings
  Sources/AnyImageKit/Resources/Picker/zh-Hans.lproj/Picker.strings
Labels: enhancement

#115 fix: check CMTime.isValid before set video pregress
  Podfile.lock
  Sources/AnyImageKit/Editor/View/Video/VideoPreview.swift
Labels: bug

#118 Fix Picker display bug
  Sources/AnyImageKit/Picker/Controller/AssetPickerViewController+Editor.swift
  Sources/AnyImageKit/Picker/Controller/AssetPickerViewController.swift
  Sources/AnyImageKit/Picker/Controller/PhotoPreviewController+Editor.swift
Labels: bug

#117 Improve editor
  AnyImageKit.xcodeproj/project.pbxproj
  Sources/AnyImageKit/Core/Extension/Core+CALayer.swift
  Sources/AnyImageKit/Core/Model/Shadow.swift
  Sources/AnyImageKit/Editor/Controller/InputTextViewController.swift
  Sources/AnyImageKit/Editor/Controller/PhotoEditorController.swift
  Sources/AnyImageKit/Editor/EditorPhotoOptionsInfo.swift
  Sources/AnyImageKit/Editor/EditorTheme.swift
  Sources/AnyImageKit/Editor/Model/Palette.swift
  Sources/AnyImageKit/Editor/Option/EditorBrushColorOption.swift
  Sources/AnyImageKit/Editor/Option/EditorMosaicOption.swift
  Sources/AnyImageKit/Editor/Option/EditorTextColor.swift
  Sources/AnyImageKit/Editor/View/Photo/Kit/ColorButton.swift
  Sources/AnyImageKit/Editor/View/Photo/Kit/ColorWell.swift
  Sources/AnyImageKit/Editor/View/Photo/ToolBar/EditorBrushToolView.swift
  Sources/AnyImageKit/Editor/View/Photo/ToolBar/EditorCropToolView.swift
  Sources/AnyImageKit/Editor/View/Photo/ToolBar/EditorEditOptionsView.swift
  Sources/AnyImageKit/Editor/View/Photo/ToolBar/EditorMosaicToolView.swift
  Sources/AnyImageKit/Editor/View/Photo/ToolBar/EditorTextToolView.swift
  Sources/AnyImageKit/Editor/View/Photo/ToolBar/EditorToolView.swift
  Sources/AnyImageKit/Picker/PickerTheme.swift
  Sources/AnyImageKit/Picker/View/Cell/AssetCell.swift
  Sources/AnyImageKit/Resources/Picker/Picker.xcassets/PhotoEdited.imageset/Contents.json
  Sources/AnyImageKit/Resources/Picker/Picker.xcassets/PhotoEdited.imageset/PhotoEdited.png
  Sources/AnyImageKit/Resources/Picker/Picker.xcassets/PhotoEdited.imageset/PhotoEdited@2x.png
  Sources/AnyImageKit/Resources/Picker/Picker.xcassets/PhotoEdited.imageset/PhotoEdited@3x.png
Labels: enhancement

#119 Improve data track
  AnyImageKit.xcodeproj/project.pbxproj
  Sources/AnyImageKit/Capture/Controller/CaptureViewController.swift
  Sources/AnyImageKit/Capture/Util/DataTrack/Capture+AnyImageEvent.swift
  Sources/AnyImageKit/Capture/Util/DataTrack/Capture+AnyImagePage.swift
  Sources/AnyImageKit/Core/Controller/AnyImageViewController.swift
  Sources/AnyImageKit/Core/Util/DataTrack/AnyImageEvent.swift
  Sources/AnyImageKit/Core/Util/DataTrack/AnyImagePage.swift
  Sources/AnyImageKit/Editor/Controller/InputTextViewController.swift
  Sources/AnyImageKit/Editor/Controller/PhotoEditorController.swift
  Sources/AnyImageKit/Editor/Controller/VideoEditorController.swift
  Sources/AnyImageKit/Editor/EditorTheme.swift
  Sources/AnyImageKit/Editor/Util/DataTrack/Editor+AnyImageEvent.swift
  Sources/AnyImageKit/Editor/Util/DataTrack/Editor+AnyImagePage.swift
  Sources/AnyImageKit/Editor/View/Video/VideoEditorCropToolView.swift
  Sources/AnyImageKit/Picker/Controller/AssetPickerViewController+Capture.swift
  Sources/AnyImageKit/Picker/Controller/AssetPickerViewController.swift
  Sources/AnyImageKit/Picker/Controller/PhotoPreviewController+Editor.swift
  Sources/AnyImageKit/Picker/Controller/PhotoPreviewController.swift
  Sources/AnyImageKit/Picker/PickerTheme.swift
  Sources/AnyImageKit/Picker/Util/DataTrack/Picker+AnyImageEvent.swift
  Sources/AnyImageKit/Picker/Util/DataTrack/Picker+AnyImagePage.swift
  Sources/AnyImageKit/Picker/View/PermissionDeniedView.swift
Labels: enhancement

#120 Fix picker user wrong index
  Sources/AnyImageKit/Picker/Controller/AssetPickerViewController+Capture.swift
Labels: bug

#121 Improve rotation
  Sources/AnyImageKit/Editor/Controller/ImageEditorController.swift
  Sources/AnyImageKit/Editor/Controller/PhotoEditorController.swift
  Sources/AnyImageKit/Editor/Extension/Editor+CGSize.swift
  Sources/AnyImageKit/Editor/Model/Photo/Data/CropData.swift
  Sources/AnyImageKit/Editor/Model/Photo/Data/RotateData.swift
  Sources/AnyImageKit/Editor/Model/Photo/PhotoEditingStack.swift
  Sources/AnyImageKit/Editor/Model/Photo/PhotoEditorCropContext.swift
  Sources/AnyImageKit/Editor/View/Photo/PhotoEditorContentView+Crop.swift
  Sources/AnyImageKit/Editor/View/Photo/PhotoEditorContentView+Getter.swift
  Sources/AnyImageKit/Editor/View/Photo/PhotoEditorContentView+InputText.swift
  Sources/AnyImageKit/Editor/View/Photo/PhotoEditorContentView.swift
  Sources/AnyImageKit/Editor/View/Photo/ToolBar/EditorEditOptionsView.swift
Labels: bug

#122 Add API Tests
  APITests/CaptureAPITests.swift
  APITests/EditorAPITests.swift
  APITests/Info.plist
  APITests/PickerAPITests.swift
  AnyImageKit.xcodeproj/project.pbxproj
Labels: enhancement

#123 Fix picker
  Sources/AnyImageKit/Picker/Controller/AssetPickerViewController.swift
  Sources/AnyImageKit/Picker/Controller/PhotoPreviewController+Editor.swift
  Sources/AnyImageKit/Picker/Controller/PhotoPreviewController.swift
Labels: bug

#124 Improve input text
  Sources/AnyImageKit/Editor/Controller/InputTextViewController.swift
  Sources/AnyImageKit/Editor/Controller/PhotoEditorController.swift
  Sources/AnyImageKit/Editor/View/Photo/Kit/TextImageView.swift
Labels: enhancement

#125 doc/0.14.0
  Documentation/DATA_TRACK.md
  Documentation/README_CN.md
  Documentation/RELEASE_NOTE.md
  Documentation/RELEASE_NOTE_CN.md
  Documentation/Wiki/EDITOR_GUIDE_CN.md
  README.md
Labels: documentation

#126 fix(Picker): Crash after take photo in iOS 14 or later
  Sources/AnyImageKit/Picker/Controller/AssetPickerViewController+Capture.swift
Labels: bug
